// @ts-nocheck
import { browser } from '@hanzo/docs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("@hanzo/docs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "build/contracts.mdx": () => import("../content/docs/build/contracts.mdx?collection=docs"), "build/index.mdx": () => import("../content/docs/build/index.mdx?collection=docs"), "build/sdks.mdx": () => import("../content/docs/build/sdks.mdx?collection=docs"), "build/subnets.mdx": () => import("../content/docs/build/subnets.mdx?collection=docs"), "build/tutorials.mdx": () => import("../content/docs/build/tutorials.mdx?collection=docs"), "learn/architecture.mdx": () => import("../content/docs/learn/architecture.mdx?collection=docs"), "learn/consensus.mdx": () => import("../content/docs/learn/consensus.mdx?collection=docs"), "learn/index.mdx": () => import("../content/docs/learn/index.mdx?collection=docs"), "learn/post-quantum.mdx": () => import("../content/docs/learn/post-quantum.mdx?collection=docs"), "learn/tokenomics.mdx": () => import("../content/docs/learn/tokenomics.mdx?collection=docs"), "nodes/archive.mdx": () => import("../content/docs/nodes/archive.mdx?collection=docs"), "nodes/full-node.mdx": () => import("../content/docs/nodes/full-node.mdx?collection=docs"), "nodes/index.mdx": () => import("../content/docs/nodes/index.mdx?collection=docs"), "nodes/validator.mdx": () => import("../content/docs/nodes/validator.mdx?collection=docs"), "reference/health.mdx": () => import("../content/docs/reference/health.mdx?collection=docs"), "reference/index.mdx": () => import("../content/docs/reference/index.mdx?collection=docs"), "reference/info.mdx": () => import("../content/docs/reference/info.mdx?collection=docs"), "reference/json-rpc.mdx": () => import("../content/docs/reference/json-rpc.mdx?collection=docs"), "reference/platform.mdx": () => import("../content/docs/reference/platform.mdx?collection=docs"), "reference/sdk-go.mdx": () => import("../content/docs/reference/sdk-go.mdx?collection=docs"), "reference/sdk-js.mdx": () => import("../content/docs/reference/sdk-js.mdx?collection=docs"), }),
};
export default browserCollections;